version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=lamb
    volumes:
      - ./mongodata:/data/db
  lamb:
    image: lamb
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      NODE_ENV: production
    links:
      - mongo
    depends_on:
      - mongo
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - 'mongo'
    ports:
      - '8081:8081'
    restart: always
